# 01-finance-exposure-to-ai-risk.rq
# Goal: Find Financial Institutions (finance:CreditInstitution, etc.) and their alignment to AI dimensions.

PREFIX gg: <https://iqns.org/v0/ai#>
PREFIX fg: <https://iqns.org/v0/fingraph#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?this ?thisLabel ?aiDimension ?aiDimensionLabel
WHERE {
    ?this a ?type .
    ?type rdfs:subClassOf* fg:Stakeholder .
    ?this skos:prefLabel ?thisLabel .
    
    # Trace mapping to AI Dimensions (gg:)
    ?this gg:mappedToDimension ?domainDimension .
    ?domainDimension skos:broadMatch* ?aiDimension .
    ?aiDimension a gg:Dimension .
    ?aiDimension skos:prefLabel ?aiDimensionLabel .
}
