PREFIX ai: <https://iqns.org/v0/ai#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?category (COUNT(?issue) AS ?count) WHERE {
  ?issue a ai:Risk ;
         ai:hasRiskCategory ?category .
} GROUP BY ?category
ORDER BY DESC(?count)
