# 01-def-ihl-compliance.rq
# Goal: Verify Autonomous Systems have IHL compliance controls.

PREFIX gg: <https://iqns.org/v1/ai#>
PREFIX defence: <https://iqns.org/v1/defgraph#>
PREFIX dod: <https://iqns.org/v1/dod-rai#>

SELECT ?this ?label ?ihlControl
WHERE {
    ?this a gg:System ;
               skos:prefLabel ?label ;
               gg:mappedToDimension defence:LegalCompliance .
               
    ?this gg:implementsControl ?ihlControl .
    ?ihlControl rdfs:subClassOf* dod:IHLCompliance .
}
